#ifndef PIXXEL_MAIN_EVENTS_H
#define PIXXEL_MAIN_EVENTS_H

#define PIXXEL_MAIN_STARTUP_INF_EID      1
#define PIXXEL_MAIN_ENABLE_SENT_INF_EID  2
#define PIXXEL_MAIN_ACK_RCVD_INF_EID    3
#define PIXXEL_MAIN_STATUS_SENT_INF_EID  4
#define PIXXEL_MAIN_STATUS_OK_INF_EID    5
#define PIXXEL_MAIN_STATUS_FAIL_ERR_EID  6
#define PIXXEL_MAIN_PIPE_ERR_EID         7
#define PIXXEL_MAIN_UNEXPECTED_MID_EID   8

#endif /* PIXXEL_MAIN_EVENTS_H */
