#ifndef PIXXEL_CONTROLLER_EVENTS_H
#define PIXXEL_CONTROLLER_EVENTS_H

#define PIXXEL_CTRL_STARTUP_INF_EID    1
#define PIXXEL_CTRL_DEV_OPEN_ERR_EID   2
#define PIXXEL_CTRL_ENABLE_INF_EID     3
#define PIXXEL_CTRL_ENABLE_ERR_EID     4
#define PIXXEL_CTRL_STATUS_INF_EID     5
#define PIXXEL_CTRL_STATUS_ERR_EID     6
#define PIXXEL_CTRL_UNKNOWN_CMD_EID    7
#define PIXXEL_CTRL_PIPE_ERR_EID       8

#endif /* PIXXEL_CONTROLLER_EVENTS_H */
